$(document).ready(function(){
	$('.mask').hide();
	$('.sign').hide();
	$('.signin').click(function(){
		$('.mask').show();
		$('.sign').show();
	});
	$('.close').click(function(){
    	$('.mask').hide();
		$('.sign').hide();
	});
})
